// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/alerts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Danh sách cảnh báo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lọc theo trạm",
                        "name": "station_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "Số giờ lùi lại",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Alert"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/forecast": {
            "get": {
                "description": "Dự báo theo hồi quy tuyến tính; bao gồm health_advice và risk_level",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Dự báo PM2.5 / AQI",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "Số bước dự báo",
                        "name": "steps",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_forecast.Result"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/heatmap": {
            "get": {
                "description": "Tọa độ và PM2.5/AQI theo thời gian cho bản đồ nhiệt",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Điểm heatmap",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "Số giờ lùi lại",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.HeatmapPoint"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/readings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readings"
                ],
                "summary": "Nhật ký bản ghi đo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lọc theo trạm",
                        "name": "station_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "Số giờ lùi lại",
                        "name": "hours",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 200,
                        "description": "Giới hạn số dòng",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.ReadingLog"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "StationKey": []
                    }
                ],
                "description": "Nhận bản ghi PM2.5/PM10 từ thiết bị. Yêu cầu header X-Station-Key khi STATION_API_KEY được cấu hình.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readings"
                ],
                "summary": "Ghi nhận dữ liệu cảm biến (ESP32)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key trạm (bắt buộc nếu server có STATION_API_KEY)",
                        "name": "X-Station-Key",
                        "in": "header"
                    },
                    {
                        "description": "Dữ liệu đo",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.ReadingInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Station"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Lấy cấu hình cảnh báo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Settings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Cập nhật cấu hình cảnh báo",
                "parameters": [
                    {
                        "description": "Ngưỡng PM2.5/AQI và Telegram",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Settings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Settings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/stations": {
            "get": {
                "description": "Trả về tất cả trạm với chỉ số AQI, PM2.5 và gauge mới nhất",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Danh sách trạm",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Station"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/stations/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Chi tiết một trạm",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station ID (1-3)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Station"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/stations/{id}/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Lịch sử đo của trạm",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station ID (1-3)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "Số giờ lùi lại",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.HistoryPoint"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/stats/readings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Thống kê bản ghi đo",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "Số giờ lùi lại",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.ReadingStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/system/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Trạng thái hệ thống",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.SystemStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/telegram/test": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Gửi tin nhắn Telegram thử",
                "parameters": [
                    {
                        "description": "Chat ID (tùy chọn, mặc định dùng cấu hình)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.TelegramTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.TelegramTestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Kiểm tra trạng thái API và kết nối PostgreSQL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ws/stations": {
            "get": {
                "description": "Kết nối WebSocket tại ws://host/ws/stations. Server broadcast JSON: ` + "`" + `{\"type\":\"stations\",\"data\":[...]}` + "`" + `",
                "tags": [
                    "realtime"
                ],
                "summary": "WebSocket cập nhật trạm realtime",
                "responses": {}
            }
        }
    },
    "definitions": {
        "github_com_web-kokhi_backend_internal_forecast.Point": {
            "type": "object",
            "properties": {
                "aqi": {
                    "type": "integer"
                },
                "forecast": {
                    "type": "boolean"
                },
                "pm25": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_forecast.Result": {
            "type": "object",
            "properties": {
                "current_pm25": {
                    "type": "number"
                },
                "health_advice": {
                    "type": "string"
                },
                "hours_until_warning": {
                    "type": "number"
                },
                "message": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_web-kokhi_backend_internal_forecast.Point"
                    }
                },
                "risk_level": {
                    "type": "string"
                },
                "slope_per_hour": {
                    "type": "number"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                },
                "sufficient_data": {
                    "type": "boolean"
                },
                "trend": {
                    "type": "string"
                },
                "will_exceed_warning": {
                    "type": "boolean"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.Alert": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "metric": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.Gauge": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.HeatmapPoint": {
            "type": "object",
            "properties": {
                "aqi": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "pm25": {
                    "type": "number"
                },
                "recorded_at": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.HistoryPoint": {
            "type": "object",
            "properties": {
                "pm10": {
                    "type": "number"
                },
                "pm25": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.ReadingInput": {
            "type": "object",
            "properties": {
                "firmware": {
                    "type": "string"
                },
                "humidity": {
                    "type": "number"
                },
                "pm10": {
                    "type": "number"
                },
                "pm25": {
                    "type": "number"
                },
                "rssi": {
                    "type": "integer"
                },
                "station_id": {
                    "type": "integer"
                },
                "temp": {
                    "type": "number"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.ReadingLog": {
            "type": "object",
            "properties": {
                "aqi": {
                    "type": "integer"
                },
                "humidity": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "pm10": {
                    "type": "number"
                },
                "pm25": {
                    "type": "number"
                },
                "quality_flag": {
                    "type": "string"
                },
                "recorded_at": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                },
                "temp": {
                    "type": "number"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.ReadingStats": {
            "type": "object",
            "properties": {
                "aqi_avg": {
                    "type": "integer"
                },
                "aqi_max": {
                    "type": "integer"
                },
                "aqi_min": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "humidity_avg": {
                    "type": "number"
                },
                "humidity_max": {
                    "type": "number"
                },
                "humidity_min": {
                    "type": "number"
                },
                "pm10_avg": {
                    "type": "number"
                },
                "pm10_max": {
                    "type": "number"
                },
                "pm10_min": {
                    "type": "number"
                },
                "pm25_avg": {
                    "type": "number"
                },
                "pm25_max": {
                    "type": "number"
                },
                "pm25_min": {
                    "type": "number"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                },
                "temp_avg": {
                    "type": "number"
                },
                "temp_max": {
                    "type": "number"
                },
                "temp_min": {
                    "type": "number"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.Settings": {
            "type": "object",
            "properties": {
                "aqi_critical": {
                    "type": "integer"
                },
                "aqi_warning": {
                    "type": "integer"
                },
                "pm25_critical": {
                    "type": "number"
                },
                "pm25_warning": {
                    "type": "number"
                },
                "telegram_chat_id": {
                    "type": "string"
                },
                "telegram_enabled": {
                    "type": "boolean"
                },
                "telegram_ready": {
                    "type": "boolean"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.Station": {
            "type": "object",
            "properties": {
                "aqi": {
                    "type": "integer"
                },
                "aqiLabel": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "gauges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.Gauge"
                    }
                },
                "humidity": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "last_seen": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "pm25": {
                    "type": "number"
                },
                "subtitle": {
                    "type": "string"
                },
                "temp": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.StationStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "last_aqi": {
                    "type": "integer"
                },
                "last_pm25": {
                    "type": "number"
                },
                "last_seen": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                }
            }
        },
        "github_com_web-kokhi_backend_internal_model.SystemStatus": {
            "type": "object",
            "properties": {
                "alerts_today": {
                    "type": "integer"
                },
                "api_status": {
                    "type": "string"
                },
                "db_status": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "readings_today": {
                    "type": "integer"
                },
                "stale_threshold_sec": {
                    "type": "integer"
                },
                "started_at": {
                    "type": "string"
                },
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_web-kokhi_backend_internal_model.StationStatus"
                    }
                },
                "stations_online": {
                    "type": "integer"
                },
                "stations_total": {
                    "type": "integer"
                },
                "uptime_sec": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid JSON body"
                }
            }
        },
        "internal_handler.HealthResponse": {
            "type": "object",
            "properties": {
                "db": {
                    "type": "string",
                    "example": "postgres"
                },
                "mode": {
                    "type": "string",
                    "example": "simulator"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_handler.TelegramTestRequest": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "internal_handler.TelegramTestResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "sent"
                }
            }
        }
    },
    "securityDefinitions": {
        "StationKey": {
            "description": "API key cho POST /api/readings (khi biến môi trường STATION_API_KEY được đặt)",
            "type": "apiKey",
            "name": "X-Station-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Web Kokhi API",
	Description:      "API giám sát chất lượng không khí — trạm đo, cảnh báo, dự báo và thống kê.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
